name: build and push docker image

on:
  workflow_dispatch:
  push:
    branches:
      - master
  
  jobs:
    build_and_push:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Docker buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Login to ghcr
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: ghcr.io/${{ github.repository_owner }}/five31:latest
